# Generated by Django 4.0.4 on 2023-03-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, max_length=32, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grantaward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=16)),
                ('award_id', models.CharField(max_length=8)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('startyear', models.IntegerField(blank=True, db_column='startYear', null=True)),
                ('startmonth', models.IntegerField(blank=True, db_column='startMonth', null=True)),
                ('endyear', models.IntegerField(blank=True, db_column='endYear', null=True)),
                ('endmonth', models.IntegerField(blank=True, db_column='endMonth', null=True)),
            ],
            options={
                'db_table': 'GrantAward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Investigator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Prereq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('title', models.CharField(max_length=128)),
                ('venue', models.CharField(blank=True, max_length=64, null=True)),
                ('kind', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Publication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.CharField(max_length=4)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=32, null=True)),
                ('room', models.CharField(blank=True, max_length=8, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'Takes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Teaches',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='Instructor',
        ),
    ]
